# Data science (Parcours) M@sm@

# Introduction à la bibliothèque numpy

In [56]:
import numpy as np

## Création d'un tableau numpy

#### Avec 'np.array()'

In [57]:
mon_tableau = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.int16)
# Création d'un tableau grace a la methode 'np.array()' de numpy de type entier
# qui prend des listes en parametre
print(type(mon_tableau))
print(mon_tableau)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Avec 'np.zeros((nombre_lignes, nombre_colonnes))'

In [58]:
# La methode 'np.zeros()' nous perment d'initialiser un tableau rempli des '0'
# il prend en parametre le nombre des lignes et celui des colonnes
print(np.zeros((3,5), dtype=np.int16))# 3, le nombre des lignes et 5 le nombre des colonnes

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### Avec 'np.ones((nombre_lignes, nombre_colonnes))'

In [59]:
# La methode 'np.ones()' nous perment d'initialiser un tableau rempli des '0'
# il prend en parametre le nombre des lignes et celui des colonnes
print(np.ones((3,7), dtype=np.int16)) # 3, le nombre des lignes et 7 le nombre des colonnes

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


#### Avec 'np.random.randn(nombre_ligne, nombre_colonne)' et 'np.empty((nombre_lignes, nombre_colonnes))'

In [60]:
# La méthode 'np.random.randn()' nous initialise un tableau numpy ayant des valeurs  aléatoires sans possibilité de déterminer un type des données
print('--- Avec np.random.randn() ---')
print(np.random.randn(3,4))
# La méthode 'np.empty()' nous initialise un tableau numpy ayant des valeurs  aléatoires avec possibilité de déterminer un type des données
print('--- Avec np.empty()')
print(np.empty((3,4), dtype=np.float64))


--- Avec np.random.randn() ---
[[-0.02982457  3.68225212  0.50404154 -0.68162731]
 [-1.45548399 -1.2532412  -0.09695496 -0.66313354]
 [-0.94139118 -0.62714593  1.35411338  0.45794504]]
--- Avec np.empty()
[[-0.02982457  3.68225212  0.50404154 -0.68162731]
 [-1.45548399 -1.2532412  -0.09695496 -0.66313354]
 [-0.94139118 -0.62714593  1.35411338  0.45794504]]


### Numpy - Méthodes ndim, shape et size
- ndim = indique la dimension du tableau
- shape = indique le nombre des lignes, des colonnes ainsi que la profondeur dans le cas des tableaux à 3 dimensions.
    - shape retourne un tuple selon qu'il s'agit d'un tableau en 1D, 2D, 3D ...
    Avec l'utilisation des tableaux 2D, nous aurons à chaque fois un tuple ayant 2  éléments; le premier indiquant le nombre des lignes et le deuxième indiquant le nombre des colonnes.
    - shape ne peut pas être modifié car il s'agit d'un tuple
    - shape[0] = Accès au nombre des lignes du tableau
    - shape[1] = Accès au nombes des colonnes du tableau
- size = indique la taille du tableau, soit le nombre d'éléments du tableau

In [61]:
print("La dimension de ce tableau est ", mon_tableau.ndim)# indique la dimension du tableau 
print("le tuple 'shape' de ce tableu est ",mon_tableau.shape)# Nombre des lignes et des colonnes dans un tuple
print('Ce tableau a ',mon_tableau.shape[0], 'ligne(s)')  # Indique le nombre des lignes
print('Ce tableau a ',mon_tableau.shape[1],'colonne(s)') # Indique le nombre des colonnes
print('Ce tableau contient',mon_tableau.size, 'éléments') # Indique la taille du tableau, soit le nombre d'éléments

La dimension de ce tableau est  2
le tuple 'shape' de ce tableu est  (3, 3)
Ce tableau a  3 ligne(s)
Ce tableau a  3 colonne(s)
Ce tableau contient 9 éléments


## Indexing et Slicing

### Indexing

In [62]:
print(mon_tableau)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [68]:
# indexing
# Accès à l'élément du table se trouvant à la première ligne; deuxième colonne
# Le 1er parametre indique la ligne et le second, indique la colonne
print(mon_tableau)
mon_tableau[0,1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

### Boolean indexing

In [93]:
T = np.random.randint(0,10,[5,5])
print(f"Matrice aléatoire\n{T}")
T[T>5] = 6 # Change toutes les valeurs supérieurs à '5' en '6'
print(f"Remplace toutes les valeurs supérieurs à '5' par '6'\n{T}")

Matrice aléatoire
[[9 3 7 6 8]
 [6 8 5 6 3]
 [1 5 1 3 5]
 [5 5 8 9 8]
 [6 5 0 3 1]]
Remplace toutes les valeurs supérieurs à '5' par '6'
[[6 3 6 6 6]
 [6 6 5 6 3]
 [1 5 1 3 5]
 [5 5 6 6 6]
 [6 5 0 3 1]]


### Slicing

In [78]:
# Slicing 
tableau_slicing = mon_tableau[0:2, 0:2]
tableau_slicing[:,:] = 10
print(tableau_slicing)
print('shape = ',tableau_slicing.shape)
print(f'Mon tableau\n{mon_tableau}')
print(f"Accès à 2 dernières colonnes\n{mon_tableau[:, -2: ]}")


[[10 10]
 [10 10]]
shape =  (2, 2)
Mon tableau
[[10 10  3]
 [10 10  6]
 [ 7  8  9]]
Accès à 2 dernières colonnes
[[10  3]
 [10  6]
 [ 8  9]]


In [83]:
b = np.zeros((4,4))
print(f'tableau\n{b}')
b[1:3, 1:3] = 8
print(f"Modification de 4 éléments au centre du tableau\n{b})")

tableau
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Modification de 4 éléments au centre du tableau
[[ 0.  0.  0.  0.]
 [ 0. 10. 10.  0.]
 [ 0. 10. 10.  0.]
 [ 0.  0.  0.  0.]])


In [88]:
# Slicing avec la notion de pas
c = np.zeros((5,5))
c[::2, ::2] = 1
c

array([[1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.]])

## Assemblage ou fusion des tableaux

Utilisation des méthodes :
* hstack
* vstack
* concatenate

In [64]:
import numpy as np


a = np.zeros((3,2), dtype=np.int16)
b = np.ones((3,2))


In [65]:
# Avec hstack

np.hstack((a,b))

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [66]:
# Avec le vstack

np.vstack((a,b))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [67]:
# Avec concatenate, il y a un autre parametre appelé axis
# axis = 0 --> Pour l'assemblage ou la fusion verticale et axis = 1 --> pour la fusion horizontale

v = np.concatenate((a,b), axis=0) # fusion verticale
h = np.concatenate((a,b), axis=1) # fusion horizontale
print(f'Fusion verticale\n{v}')
print(f"Fusion horizontale\n{h}")

fusion verticale
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Fusion horizontale
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]
