# Data science (Parcours)

# Introduction à la bibliothèque numpy

In [2]:
import numpy as np

## Création d'un tableau numpy

#### Avec 'np.array()'

In [14]:
mon_tableau = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.int16)
# Création d'un tableau grace a la methode 'np.array()' de numpy de type entier
# qui prend des listes en parametre
print(type(mon_tableau))
print(mon_tableau)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Avec 'np.zeros((nombre_lignes, nombre_colonnes))'

In [4]:
# La methode 'np.zeros()' nous perment d'initialiser un tableau rempli des '0'
# il prend en parametre le nombre des lignes et celui des colonnes
print(np.zeros((3,5), dtype=np.int16))# 3, le nombre des lignes et 5 le nombre des colonnes

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### Avec 'np.ones((nombre_lignes, nombre_colonnes))'

In [5]:
# La methode 'np.ones()' nous perment d'initialiser un tableau rempli des '0'
# il prend en parametre le nombre des lignes et celui des colonnes
print(np.ones((3,7), dtype=np.int16)) # 3, le nombre des lignes et 7 le nombre des colonnes

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


#### Avec 'np.random.randn(nombre_ligne, nombre_colonne)' et 'np.empty((nombre_lignes, nombre_colonnes))'

In [6]:
# La méthode 'np.random.randn()' nous initialise un tableau numpy ayant des valeurs  aléatoires sans possibilité de déterminer un type des données
print('--- Avec np.random.randn() ---')
print(np.random.randn(3,4))
# La méthode 'np.empty()' nous initialise un tableau numpy ayant des valeurs  aléatoires avec possibilité de déterminer un type des données
print('--- Avec np.empty()')
print(np.empty((3,4), dtype=np.float64))


--- Avec np.random.randn() ---
[[-0.7188331   1.02730555 -0.36310517  0.84765996]
 [ 1.97977417  1.15368342 -0.39140427  0.18032966]
 [-0.68993904 -0.53810661  1.32681481  1.60167453]]
--- Avec np.empty()
[[-0.7188331   1.02730555 -0.36310517  0.84765996]
 [ 1.97977417  1.15368342 -0.39140427  0.18032966]
 [-0.68993904 -0.53810661  1.32681481  1.60167453]]


### Numpy - Méthodes ndim, shape et size
- ndim = indique la dimension du tableau
- shape = indique le nombre des lignes, des colonnes ainsi que la profondeur dans le cas des tableaux à 3 dimensions.
    - shape retourne un tuple selon qu'il s'agit d'un tableau en 1D, 2D, 3D ...
    Avec l'utilisation des tableaux 2D, nous aurons un à chaque fois un tuple ayant 2  éléments; le premier indiquant le nombre des lignes et le deuxième indiquant le nombre des colonnes.
    - shape ne peut pas être modifié car il s'agit d'un tuple
    - shape[0] = Accès au nombre des lignes du tableau
    - shape[1] = Accès au nombes des colonnes du tableau
- size = indique la taille du tableau, soit le nombre d'éléments du tableau

In [7]:
print("La dimension de ce tableau est ", mon_tableau.ndim)# indique la dimension du tableau 
print("le tuple 'shape' de ce tableu est ",mon_tableau.shape)# Nombre des lignes et des colonnes dans un tuple
print('Ce tableau a ',mon_tableau.shape[0], 'ligne(s)')  # Indique le nombre des lignes
print('Ce tableau a ',mon_tableau.shape[1],'colonne(s)') # Indique le nombre des colonnes
print('Ce tableau contient',mon_tableau.size, 'éléments') # Indique la taille du tableau, soit le nombre d'éléments

La dimension de ce tableau est  2
le tuple 'shape' de ce tableu est  (3, 3)
Ce tableau a  3 ligne(s)
Ce tableau a  3 colonne(s)
Ce tableau contient 9 éléments


## Indexing, Slicing et Masking

In [15]:
print(mon_tableau)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
# Accès à l
mon_tableau[0,1]

2